
spring:
  application:
    name: security-review
  datasource:
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    web: error
    com.pacifique.security.review.controller: debug

resend:
  api-key: ${RESEND_APIKEY}
  api-url: https://api.resend.com/emails
  from: ${RESEND_ADMIN_EMAIL}
security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration: 86400000
    refresh-token:
      expiration: 604800000
    super-admin: ${SUPER_ADMIN}


springdoc:
  swagger-ui:
    path: /api-docs
---
spring:
  config:
    activate:
      on-profile: docker
  datasource.url: ${DOCKER_DATABASE_URL}

logging:
  level:
    root: warn