name: Spring boot security CI & Test

on:
  pull_request:
  push:
    branches:
      - main
      - ft/reconfig-app
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RESEND_API-KEY: ${{ secrets.RESEND_APIKEY }}
      RESEND_FROM: ${{ secrets.RESEND_ADMIN_EMAIL }}
      SECURITY_JWT_SECRET-KEY: ${{ secrets.SECRET_KEY }}
      SECURITY_JWT_SUPER-ADMIN: ${{ secrets.SUPER_ADMIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Verify Docker availability (for Testcontainers)
        run: docker info

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build and run tests
        run: ./gradlew clean build --info

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: build/libs/*.jar
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker tag
        run: |
          docker tag spring-security-review-one-main paccy/advanced-spring-security:latest
          docker tag spring-security-review-one-main paccy/advanced-spring-security:${{ github.sha }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: paccy/advanced-spring-security

      - name: Build and Push
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/paccy/advanced-spring-security
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
